import type { INestApplication } from '@nestjs/common';
import { HEADERS_METADATA, METHOD_METADATA, PATH_METADATA } from '@nestjs/common/constants';
import type { ModulesContainer } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule, type OpenAPIObject } from '@nestjs/swagger';
import type {
  HeaderObject,
  OperationObject,
  ParameterObject,
  PathItemObject,
  ResponseObject,
} from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

import { IS_PUBLIC, SKIP_TENANT } from '../auth/public.decorator';
import { REQUIRE_CSRF } from '../auth/csrf.guard';
import metadata from '../metadata';
import { ACCEPTED_CREDENTIALS, type Credential } from './accepted-credentials.decorator';
import { SHARED_SCHEMAS } from './openapi-components';
import { normalizeOpenApiDocument } from './openapi-normalize';
import { RATE_LIMIT_HEADERS, type RateLimitHeaders } from './rate-limit-headers.decorator';

/** OpenAPI dialect for Phase 1C.3 (ADR G7). */
export const OPENAPI_VERSION = '3.0.3';
/** The single document route, below the global prefix. */
export const OPENAPI_DOCUMENT_ROUTE = 'openapi.json';
/** The development-only Swagger UI, below the global prefix. */
export const OPENAPI_UI_ROUTE = 'docs';

/** Stable operation ids: `<Controller without suffix>_<handler>`. */
export function operationIdFor(controllerName: string, methodName: string): string {
  return `${controllerName.replace(/Controller$/, '')}_${methodName}`;
}

let metadataLoaded: Promise<void> | undefined;

/**
 * The committed plugin metadata (`src/metadata.ts`, generated by
 * `scripts/openapi-metadata.ts`) is the single source of DTO schemas for the
 * build, Jest and the generator alike (ADR G5). Loaded once per process.
 */
function loadPluginMetadata(): Promise<void> {
  metadataLoaded ??= SwaggerModule.loadPluginMetadata(metadata);
  return metadataLoaded;
}

/**
 * Builds the OpenAPI document for an application (Phase 1C.3). The one
 * factory behind the served document, the generator and the contract tests.
 * `app` needs only what the Swagger scanner reads: the module container, the
 * application config (global prefix) and the HTTP adapter.
 */
export async function buildOpenApiDocument(app: INestApplication): Promise<OpenAPIObject> {
  await loadPluginMetadata();

  const config = new DocumentBuilder()
    .setOpenAPIVersion(OPENAPI_VERSION)
    .setTitle('Alendei Communications Cloud API')
    .setDescription(
      'ACC control-plane API. Envelopes: `{data}` for a resource, `{data, page}` for a cursor-paginated list, `{error}` for every failure (`API.md` §7–§8).',
    )
    .setVersion('v1')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'A signed-in user session: `Authorization: Bearer <access token>`.',
      },
      'userSession',
    )
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'ak_(live|test)_<16 characters>.<secret>',
        description:
          'An API key, sent in the same header as a session token: `Authorization: Bearer ak_live_…`. Bound to one organization; never holds platform or reseller authority.',
      },
      'apiKey',
    )
    .addCookieAuth(
      'acc_refresh',
      {
        type: 'apiKey',
        in: 'cookie',
        name: 'acc_refresh',
        description:
          'The httpOnly refresh cookie, path-scoped to `/api/v1/auth`. Accepted only together with the `X-Acc-Refresh` header.',
      },
      'refreshCookie',
    )
    .build();

  const document = SwaggerModule.createDocument(app, config, {
    operationIdFactory: operationIdFor,
    extraModels: [...SHARED_SCHEMAS],
  });

  applyCrossCuttingContract(document, collectRouteFacts(app));
  return normalizeOpenApiDocument(document);
}

/** What the runtime route metadata says about one operation. */
export interface RouteFacts {
  readonly operationId: string;
  readonly isPublic: boolean;
  readonly noTenant: boolean;
  readonly csrf: boolean;
  readonly credentials: readonly Credential[] | undefined;
  readonly rateLimitHeaders: RateLimitHeaders;
  readonly staticHeaders: ReadonlyArray<{ name: string; value: string }>;
}

/** Reads each registered handler's metadata, keyed by operation id. */
export function collectRouteFacts(app: INestApplication): Map<string, RouteFacts> {
  const container = (app as unknown as { container: { getModules(): ModulesContainer } }).container;
  const facts = new Map<string, RouteFacts>();
  for (const module of container.getModules().values()) {
    for (const wrapper of module.controllers.values()) {
      const controller = wrapper.metatype as (new (...args: never[]) => unknown) | null;
      if (!controller) continue;
      const prototype = controller.prototype as Record<string, unknown>;
      for (const name of Object.getOwnPropertyNames(prototype)) {
        const handler = prototype[name];
        if (name === 'constructor' || typeof handler !== 'function') continue;
        if (Reflect.getMetadata(METHOD_METADATA, handler) === undefined) continue;
        if (Reflect.getMetadata(PATH_METADATA, handler) === undefined) continue;
        const read = <T>(key: string): T | undefined =>
          (Reflect.getMetadata(key, handler) as T | undefined) ??
          (Reflect.getMetadata(key, controller) as T | undefined);
        const isPublic = read<boolean>(IS_PUBLIC) === true;
        const operationId = operationIdFor(controller.name, name);
        facts.set(operationId, {
          operationId,
          isPublic,
          noTenant: read<boolean>(SKIP_TENANT) === true,
          csrf: read<boolean>(REQUIRE_CSRF) === true,
          credentials: read<Credential[]>(ACCEPTED_CREDENTIALS),
          rateLimitHeaders:
            read<RateLimitHeaders>(RATE_LIMIT_HEADERS) ?? (isPublic ? 'none' : 'general'),
          staticHeaders:
            (Reflect.getMetadata(HEADERS_METADATA, handler) as
              Array<{ name: string; value: string }> | undefined) ?? [],
        });
      }
    }
  }
  return facts;
}

const header = (description: string, required = false): HeaderObject => ({
  description,
  required,
  schema: { type: 'string' },
});

const CORRELATION_RESPONSE_HEADERS: Record<string, HeaderObject> = {
  'X-Correlation-Id': header(
    'The correlation id: the caller-supplied UUID when valid, otherwise a new one.',
    true,
  ),
  'X-Request-Id': header('A new id for this request.', true),
};

const GENERAL_LIMIT_HEADERS: Record<string, HeaderObject> = {
  'X-RateLimit-Limit': header(
    'General per-principal limiter: requests allowed in the window. Sent once authentication has succeeded, so absent on a `401` and on refusals raised before the limiter runs.',
  ),
  'X-RateLimit-Remaining': header('General limiter: requests left in the window.'),
  'X-RateLimit-Reset': header('General limiter: seconds until the window resets.'),
};

const BUCKET_LIMIT_HEADERS: Record<string, HeaderObject> = {
  'X-RateLimit-Limit': header(
    'Per-address authentication bucket: attempts allowed. Sent once the bucket has been consumed (not on a request refused earlier, such as a validation or CSRF failure). This bucket sends no `X-RateLimit-Reset`.',
  ),
  'X-RateLimit-Remaining': header('Per-address authentication bucket: attempts left.'),
};

const RETRY_AFTER: Record<string, HeaderObject> = {
  'Retry-After': header('Seconds to wait before retrying.', true),
};

/**
 * Adds the contract every operation shares, from runtime metadata rather than
 * per-handler repetition: request headers (`X-Correlation-Id`,
 * `X-Causation-Id`, `X-Acc-Organization`, `X-Acc-Refresh`), response headers
 * (`X-Correlation-Id`, `X-Request-Id`, the rate-limit headers where they
 * actually apply, `Retry-After` on `429`, and each handler's static `@Header`s
 * on its success responses).
 */
function applyCrossCuttingContract(document: OpenAPIObject, facts: Map<string, RouteFacts>): void {
  for (const pathItem of Object.values(document.paths) as PathItemObject[]) {
    for (const method of ['get', 'put', 'post', 'delete', 'patch', 'head', 'options'] as const) {
      const operation = pathItem[method] as OperationObject | undefined;
      if (!operation?.operationId) continue;
      const fact = facts.get(operation.operationId);
      if (!fact) continue;

      const parameters = (operation.parameters ?? []) as ParameterObject[];
      parameters.push(
        {
          name: 'X-Correlation-Id',
          in: 'header',
          required: false,
          description: 'Optional caller-supplied UUID; any other value is replaced by a new id.',
          schema: { type: 'string', format: 'uuid' },
        },
        {
          name: 'X-Causation-Id',
          in: 'header',
          required: false,
          description:
            'Optional UUID of the event or request that caused this one; any other value is ignored.',
          schema: { type: 'string', format: 'uuid' },
        },
      );
      if (!fact.isPublic && !fact.noTenant) {
        parameters.push({
          name: 'X-Acc-Organization',
          in: 'header',
          required: false,
          description:
            'Selects the organization to act in (`API.md` §3). Required when the principal can reach more than one; an organization outside the principal’s scope is refused.',
          schema: { type: 'string', format: 'uuid' },
        });
      }
      if (fact.csrf) {
        parameters.push({
          name: 'X-Acc-Refresh',
          in: 'header',
          required: true,
          description:
            'CSRF marker for the cookie-authenticated routes: any value; its absence is `403 AUTHZ_PERMISSION_DENIED`.',
          schema: { type: 'string' },
        });
      }
      operation.parameters = parameters;

      for (const [status, response] of Object.entries(operation.responses ?? {}) as Array<
        [string, ResponseObject]
      >) {
        const code = Number(status);
        const headers: Record<string, HeaderObject> = {
          ...(response.headers as Record<string, HeaderObject> | undefined),
          ...CORRELATION_RESPONSE_HEADERS,
        };
        const limit =
          fact.rateLimitHeaders === 'general'
            ? code === 401
              ? {}
              : GENERAL_LIMIT_HEADERS
            : fact.rateLimitHeaders === 'bucket'
              ? BUCKET_LIMIT_HEADERS
              : fact.rateLimitHeaders === 'general-or-bucket'
                ? { ...BUCKET_LIMIT_HEADERS, ...GENERAL_LIMIT_HEADERS }
                : {};
        Object.assign(headers, limit);
        if (code === 429) Object.assign(headers, RETRY_AFTER);
        if (code >= 200 && code < 300) {
          for (const { name, value } of fact.staticHeaders) {
            headers[name] = { ...header(`Always \`${value}\`.`, true) };
          }
        }
        response.headers = headers;
      }
    }
  }
}
